/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mascill_serial_port_SerialPort */

#ifndef _Included_com_mascill_serial_1port_SerialPort
#define _Included_com_mascill_serial_1port_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mascill_serial_port_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;IZI)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_mascill_serial_1port_SerialPort_open
        (JNIEnv *, jclass, jstring, jint, jboolean, jint);

/*
 * Class:     com_mascill_serial_port_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mascill_serial_1port_SerialPort_close
        (JNIEnv *, jobject);

/*
 * Class:     com_mascill_serial_port_SerialPort
 * Method:    setParity
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mascill_serial_1port_SerialPort_setParity
        (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif



