name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /usr/local/lib/android/sdk

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      # Accept SDK licenses
      - name: Accept Android SDK licenses
        run: yes | "${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager" --licenses

      # Install required SDK/NDK/CMake versions for the build
      - name: Install Android SDK components
        run: |
          "${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager" \
            "platforms;android-36" \
            "build-tools;34.0.0" \
            "cmake;3.22.1" \
            "ndk;28.0.12433566"

      # Build LIBRARY module only (avoid building the sample app)
      - name: Build library (release)
        run: ./gradlew :serial-port:clean :serial-port:assembleRelease
